# dbt_project/models/staging/schema.yml

version: 2

models:

  - name: stg_sales

    columns:

      - name: customer_id
        tests:
          - not_null

      - name: amount
        tests:
          - not_null

      - name: order_id
        tests:
          - not_null
